environment:
  target_network: "172.16.89.130"
  max_steps: 100
  real_execution: true
  render_mode: "ansi"
  reward_config:
    discover_host: 5.0
    open_port: 1.0
    service_identified: 2.0
    os_identified: 3.0
    vulnerability_found: 10.0
    successful_exploit: 50.0
    privilege_escalation: 75.0
    lateral_movement: 20.0
    timeout_penalty: -1.0
    failed_action: -2.0
    redundant_action: -0.5

agent:
  model_type: "dueling_dqn"  # Options: dueling_dqn, dqn, conv_dqn, hybrid_dqn
  hidden_dim: 256
  learning_rate: 0.001
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_min: 0.05  # Will be mapped to epsilon_final
  epsilon_frames: 100000  # Number of frames over which to anneal epsilon
  buffer_size: 100000  # Will be mapped to memory_size
  batch_size: 64
  target_update_freq: 10
  grad_clip_value: 1.0
  device: "cuda"  # Options: cuda, cpu

training:
  num_episodes: 100
  eval_freq: 100
  save_freq: 500
  max_steps_per_episode: 100
  early_stopping_patience: 20
  checkpoint_dir: "models/checkpoints"
  log_dir: "logs"
  use_wandb: false
  wandb_project: "cyberrl"